server:
  port: 8080
spring:
  application:
    name: mybatis-sample
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Jovaunn1
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
    hikari:
      pool-name: hikari-pool
      minimum-idle: 10
      #连接只读数据库时配置为true， 保证安全
      read-only: false
      #等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connection-timeout: 30000
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 600000
      #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL
      #wait_timeout参数（show variables like '%timeout%';）
      max-lifetime: 1800000
      #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      maximum-pool-size: 60
      connection-test-query: SELECT 1
mybatis:
  type-aliases-package: may.i.jhq.model
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
logging:
  level:
    may.i.jhq.mapper: trace


